### ISSUE TITLE
Assets wouldn't migrate. Had to adjust code

### ISSUE THREAD

**Issue by simonhamp** [statamic/migrator#79]
My v2 assets were structure liked this:

```
 / (root)
 | - assets/
   | - collections/
   | - pages/
```

The containers here being `collections` and `pages` etc.

The migrator couldn't find these files in the root of my v3 site, event though the path to them was correct in the `site/content/assets/` YAML files: `assets/collections`.

I guess it wanted each _container_ to be in the root, but that wasn't clear from the docs.

To fix this, in `AssetContainerMigrator`, I commented out the line that explodes the path ([180] I think):

```php
// $path = collect(explode('/', Arr::get($config, 'path')))->filter()->last();
```

**Comment by sjclark** [comment]
I ran into this same problem and your suggested fix seems to have fixed things for me - migration appears to have continued correctly.

**Comment by jesseleite** [comment]
> I guess it wanted each container to be in the root, but that wasn't clear from the docs.

In readme since 2019 😊 ❤️

Site migrator instructions...

![CleanShot 2022-07-15 at 11 17 16](https://user-images.githubusercontent.com/5187394/179253625-718abdf9-03a0-4ab4-b8d6-7cf8b5029a7d.png)

Individual asset container migrator instructions...

![CleanShot 2022-07-15 at 11 27 18](https://user-images.githubusercontent.com/5187394/179255568-3a40adcb-fa7d-4e27-a24e-6f66def3be2b.png)

Closing this, but open to a PR if we need more clarity! 👍

**Comment by pdipatrizio** [comment]
@jesseleite In my case, I understood that the docs wanted to see the assets in the root, but doing it that way was a burden. We have 19 folders in /assets and 2 of them (/content and /resources) conflict with existing folders in the root. In my opinion, it just feels much cleaner to drop a single /assets folder (with many asset containers) into the root, rather than dropping many asset containers into the root.

**Comment by jesseleite** [comment]
@pdipatrizio Interesting. You can also copy asset container folders into a `migrator` folder relative to your site root, to avoid naming conflicts, but I'm now realizing this part isn't documented, so is a hidden feature: https://github.com/statamic/migrator/blob/master/src/AssetContainerMigrator.php#L184-L185

**Comment by jesseleite** [comment]
^ Made this a little more forgiving. Should now also migrate from original configured path if locally nested 👍
